#!/bin/bash

# Helper script to set up Git repository for file syncing
# This creates a separate Git repo for uploaded files

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Setting up Git repository for file syncing..."
echo ""

# Check if git is available
command -v git >/dev/null 2>&1 || { echo "Error: git is required but not installed"; exit 1; }

# Ask for repository URL
read -p "Enter Git repository URL for files (e.g., git@github.com:user/files-repo.git): " GIT_REPO_URL

if [ -z "$GIT_REPO_URL" ]; then
    echo "Error: Git repository URL is required"
    exit 1
fi

# Ask for branch name
read -p "Enter branch name (default: main): " BRANCH_NAME
BRANCH_NAME=${BRANCH_NAME:-main}

# Initialize local temp repo
TEMP_DIR="${PROJECT_DIR}/.files-git-temp"
if [ -d "${TEMP_DIR}" ]; then
    echo "Removing existing temp directory..."
    rm -rf "${TEMP_DIR}"
fi

echo "Initializing Git repository..."
mkdir -p "${TEMP_DIR}"
cd "${TEMP_DIR}"
git init
git remote add origin "${GIT_REPO_URL}"

# Try to pull existing repo, or create initial commit
if git fetch origin "${BRANCH_NAME}" 2>/dev/null; then
    echo "Found existing repository, pulling latest..."
    git checkout -b "${BRANCH_NAME}" "origin/${BRANCH_NAME}" 2>/dev/null || git checkout "${BRANCH_NAME}"
else
    echo "Creating new repository..."
    git checkout -b "${BRANCH_NAME}"
    touch .gitkeep
    git add .gitkeep
    git commit -m "Initial commit for files repository"
    git push -u origin "${BRANCH_NAME}"
fi

# Create or update deployment config file
CONFIG_FILE="${PROJECT_DIR}/.deployment-config"
echo ""
echo "Updating deployment configuration..."

# Create config file if it doesn't exist
if [ ! -f "${CONFIG_FILE}" ]; then
    echo "# Deployment Configuration" > "${CONFIG_FILE}"
    echo "# Generated by setup-files-git.sh" >> "${CONFIG_FILE}"
    echo "" >> "${CONFIG_FILE}"
fi

# Update or add FILES_GIT_REPO
if grep -q "^FILES_GIT_REPO=" "${CONFIG_FILE}" 2>/dev/null; then
    # Update existing entry
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^FILES_GIT_REPO=.*|FILES_GIT_REPO=\"${GIT_REPO_URL}\"|" "${CONFIG_FILE}"
    else
        # Linux
        sed -i "s|^FILES_GIT_REPO=.*|FILES_GIT_REPO=\"${GIT_REPO_URL}\"|" "${CONFIG_FILE}"
    fi
else
    # Add new entry
    echo "FILES_GIT_REPO=\"${GIT_REPO_URL}\"" >> "${CONFIG_FILE}"
fi

# Update or add FILES_GIT_BRANCH
if grep -q "^FILES_GIT_BRANCH=" "${CONFIG_FILE}" 2>/dev/null; then
    # Update existing entry
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^FILES_GIT_BRANCH=.*|FILES_GIT_BRANCH=\"${BRANCH_NAME}\"|" "${CONFIG_FILE}"
    else
        # Linux
        sed -i "s|^FILES_GIT_BRANCH=.*|FILES_GIT_BRANCH=\"${BRANCH_NAME}\"|" "${CONFIG_FILE}"
    fi
else
    # Add new entry
    echo "FILES_GIT_BRANCH=\"${BRANCH_NAME}\"" >> "${CONFIG_FILE}"
fi

# Ensure UPLOADED_FILES_METHOD is set to git
if grep -q "^UPLOADED_FILES_METHOD=" "${CONFIG_FILE}" 2>/dev/null; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^UPLOADED_FILES_METHOD=.*|UPLOADED_FILES_METHOD=\"git\"|" "${CONFIG_FILE}"
    else
        sed -i "s|^UPLOADED_FILES_METHOD=.*|UPLOADED_FILES_METHOD=\"git\"|" "${CONFIG_FILE}"
    fi
else
    echo "UPLOADED_FILES_METHOD=\"git\"" >> "${CONFIG_FILE}"
fi

echo ""
echo "✓ Git repository setup complete!"
echo ""
echo "Configuration saved to: ${CONFIG_FILE}"
echo "  Repository: ${GIT_REPO_URL}"
echo "  Branch: ${BRANCH_NAME}"
echo ""
echo "The deployment scripts will automatically use these settings."

